### ISSUE TITLE
Add feature to remind registered organizations via email to upload new datasets

### ISSUE THREAD

**Issue by ignatiusukwuoma** [CodeForAfrica/openAFRICA#8]
Organizations within the platform upload the most reliable datasets. There needs to be a way to remind and motivate them to add more datasets. One way to motivate them is through visible engagement (comments and likes) by users on datasets. Also, reminding the organization about adding new datasets will help them keep it in mind. 

I suggest that one of the comments extensions available be installed on OpenAfrica and a Favorite/Like feature be built. Also, building a feature that sends an email to the creators of organizations three months after the last dataset was added (and quarterly from then until a new dataset is added) would assist OpenAfrica achieve its aim of  becoming the largest independent repository of open data on the African continent.

**Comment by shemogumbe** [comment]
I like the idea of opening engagement, however, on the idea of reminders, I feel the idea of putting up data requests serves this purpose way better...

> data is only as important as it's uses

>

**Comment by andela-iukwuoma** [comment]
@shemogumbe No one gets notified when a datarequest is made. An organization that has the requested data might not even know that someone requested for it if they do not visit the site often. Sahara Reporters uploaded two datasets on OpenAfrica in 2015 and none ever since, is it that they do not have new datasets or they didn't remember to add them. I believe it's the latter. OpenAfrica should be able to reach its organizations via emails and not wait until they visit the site.

**Comment by DavidLemayian** [comment]
Thanks @andela-iukwuoma. This looks like quite the plugin. Could you spec out the functions and ways the user can manage these notifications here? I'd figure they'd be part of the activity stream notifications already built in?

**Comment by DavidLemayian** [comment]
This would be better as an analytics/stats integration elsewhere.
